### ISSUE TITLE
lavapick: only one mese wire from default:mese

### ISSUE THREAD

**Issue by tchncs** [tenplus1/mobs_monster#1]
Hi, i noticed that the lavapick just give one wire by digging default:mese.
It should be 162, shouldnt it?

**Comment by tenplus1** [comment]
Which mod are you referring to ?

**Comment by tchncs** [comment]
`:mobs:pick_lava`
https://github.com/tenplus1/mobs_monster/blob/master/lava_flan.lua#L76

**Comment by tenplus1** [comment]
Fixed :)

**Comment by tchncs** [comment]
Wonderful, thank you :)
