### ISSUE TITLE
Taming monsters?

### ISSUE THREAD

**Issue by farooqkz** [tenplus1/mobs_monster#9]
Is there anyway to tame a monster?
If not how about adding it?
I'm not sure about this, yet. but this could be an example:
We tame a dirt monster and he doesn't attack us anymore, instead other people coming close to them and animals.
Again, I'm not sure it's a good idea.

**Comment by tenplus1** [comment]
Lets leave this functionality for a separate mod, monsters are there to attack players and hopefully force them to build a house or craft armor and weapons to protect themselves, it's a progression tool for now :)

**Comment by farooqkz** [comment]
Right
